// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snqtnznhmklgyxbthfoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNucXRuem5obWtsZ3l4YnRoZm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTQxNzgsImV4cCI6MjA2OTI3MDE3OH0.gW3MjBsrv1F4UEBAGYJlz52zws7Mnh8MJaKFN5PfiCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});